### ISSUE TITLE
Error: Failed to choose a D3D11 Adapter.

### ISSUE THREAD

**Issue by yardenshoham** [aws-samples/deploying-unreal-engine-pixel-streaming-server-on-ec2#2]
I looked at the logs, I saw this:
`A D3D11-compatible GPU (Feature Level 11.0, Shader Model 5.0) is required to run the engine.`

I think the default instance doesn't have a compatible GPU. I don't know how to proceed.
![image](https://user-images.githubusercontent.com/20454870/105231959-5aa29000-5b70-11eb-8c73-ad030f72b38c.png)

Thus, the build is not running. Please note the webserver does start:
![image](https://user-images.githubusercontent.com/20454870/105221198-72264c80-5b61-11eb-9bae-001ee51c4c81.png)
![image](https://user-images.githubusercontent.com/20454870/105221217-7bafb480-5b61-11eb-8c69-002f8698bad3.png)

**Comment by sebrk** [comment]
What instance are you running?

I was using g4ad.xlarge. Even though it was not necessary I installed the vGaming drivers instead of workstation drivers that are default. That was only to get RTX, not necessary for streaming unless your project has RTX ON.

**Comment by yardenshoham** [comment]
> What instance are you running?

I am using the default values of the CloudFormation template. So the instance is `g4dn.xlarge`.

> I was using g4ad.xlarge. Even though it was not necessary I installed the vGaming drivers instead of workstation drivers that are default. That was only to get RTX, not necessary for streaming unless your project has RTX ON?
> 
> I remember getting similar errors when running RTX-stuff on the default instance.

Very interesting @sebrk. Can you tell me how to install those drivers? Maybe that'll help me solve my issue.

@kashman-amzn I think this shows a pattern with the default configuration. BTW, I am trying to deploy the [pixel streaming demo](https://docs.unrealengine.com/en-US/Resources/Showcases/PixelStreamingShowcase/index.html), nothing special.

**Comment by sebrk** [comment]
Do you have RTX on?

instructions here: https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html#nvidia-gaming-driver

**Comment by yardenshoham** [comment]
@sebrk **Amazing!**, you fixed it! I am not sure if I required RTX or not but this was the solution. I followed the steps you linked until step 3 and that was enough. Do you know how to automate this process or put it in the CloudFormation template?

**Comment by sebrk** [comment]
> @sebrk **Amazing!**, you fixed it! I am not sure if I required RTX or not but this was the solution. I followed the steps you linked until step 3 and that was enough. Do you know how to automate this process or put it in the CloudFormation template?

Great! You probably had a bad case of drivers from the start. I have not automated this but googling around should help you find information on it.

**Comment by yardenshoham** [comment]
@kashman-amzn could you modify the CloudFormation template to include the aforementioned drivers?

**Comment by kashman-amzn** [comment]
Thank you for your collaboration on this issue and working through and identifying the need for the NVIDIA gaming driver. The GRID drivers are installed as part of the NICE DCV installation, and works for many UE4 projects but we will modify the CloudFormation to switch to the gaming driver. Again thanks for digging into this.

**Comment by sebrk** [comment]
Excellent @kashman-amzn!

**Comment by yardenshoham** [comment]
@kashman-amzn thank you very much! When do you think we'll have the new CloudFormation?

**Comment by yardenshoham** [comment]
@kashman-amzn I saw your recent commit. If I wanted to use the NVIDIA gaming driver what steps should I take to modify the CloudFormation template?

**Comment by kashman-amzn** [comment]
I am planning to get to this but it may not happen until next week. One way you can do this is to add a silent install of the latest NVIDIA EC2 gaming driver in the bootstrap script. You could also execute it in the CFn script by adding the file to the download items and executing the silent install. Documentation on NVIDIA driver installation can be found here: https://docs.aws.amazon.com/AWSEC2/latest/WindowsGuide/install-nvidia-driver.html

**Comment by kashman-amzn** [comment]
I have added the installation of the .NET Framework and run the UE4PrereqSetup that is bundled with the build by the engine. This should ensure current and future dependencies are resolved before running the pixel streaming build. As far as the NVIDIA gaming driver, I have added a note on how to install that driver if desired, but with the prerequisite installed the Unreal Engine Pixel Streaming demo that failed before now succeeds and streams as expected at 60fps.

**Comment by yardenshoham** [comment]
Hey @kashman-amzn, I used the latest scripts and I still get the same issue trying to deploy the pixel streaming demo. Are you sure you were able to deploy it?

**Comment by yardenshoham** [comment]
I was able to deploy it by changing the `DiskSize` to `45GB`.

**Comment by kashman-amzn** [comment]
That is great. I will be increasing the default storage value to 50GB so that larger sized projects will work by default.
